<?xml version="1.0" ?>
<testCase duration="0.000" fail="0" name="SET-251" pass="0" startdate="20160216" starttime="123829">
	<block fail="0" pass="0"/>
	<block fail="0" pass="0"/>
	<block fail="0" pass="0">
		<block fail="0" pass="0">
			<call fail="1" pass="0">functions.addValues(vars.a, &quot;A&quot;)</call>
			<call fail="0" pass="0">functions.raiseError('Intentional exception in execution phase')</call>
			<call fail="0" pass="0">functions.raiseError('Should not run')</call>
		</block>
		<block fail="0" pass="0">
			<call fail="0" pass="0">functions.raiseError('Should not run')</call>
		</block>
	</block>
	<block fail="0" pass="0">
		<call fail="0" pass="0">functions.raiseError('Should not run')</call>
	</block>
</testCase>
